[phases.setup]
nixPkgs = [
    "libGL", 
    "libglvnd", 
    "mesa", 
    "xorg.libX11", 
    "xorg.libXext",
    "glib",
    "stdenv.cc.cc.lib"
]

[phases.build]
dependsOn = ["setup"]

[start]
cmd = "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT"