import {
  Calendar,
  Heart,
  Palette,
  TrendingUp,
  Search,
  Sparkles,
  Droplets,
  MessageCircle,
  TriangleAlert,
  Bot,
  Zap,
  TestTube,
  Brush,
  Star,
  Camera,
  Award,
  BookOpen,
  Apple,
  Pill,
  Waves,
  Beaker,
  Wand2,
  Shirt,
  CreditCard,
  Leaf,
  Dumbbell,
  Brain,
  Sun,
  Shield,
  Target,
  Lightbulb,
  Stethoscope,
  Salad,
  AlarmClock,
} from "lucide-react";

export const categoryItemsData = [
  {
    title: "Skincare",
    icon: Droplets,
    items: [
      {
        title: "Derm Direct",
        icon: Stethoscope,
        bg: "bg-[linear-gradient(45deg,#BBF7D0_0%,#34D399_100%)]",
        new: true,
        route: "/skincare/chat",
        scanRoute: "/skin-analysis",
        description: "Personalized advice",
      },
      {
        title: "Trend Truth",
        icon: TrendingUp,
        bg: "bg-[linear-gradient(45deg,#FEF08A_0%,#FBBF24_100%)]",
        route: "/skincare/trend-analysis",
        scanRoute: "/product-analysis",
        description: "Skincare trends",
      },
      {
        title: "Formula Finder",
        icon: TestTube,
        bg: "bg-[linear-gradient(45deg,#99F6E4_0%,#22D3EE_100%)]",
        route: "/skincare/check-ingredients",
        scanRoute: "/product-analysis",
        description: "Ingredient checker",
      },
      {
        title: "Skin Strategy",
        icon: Calendar,
        bg: "bg-[linear-gradient(45deg,#C7D2FE_0%,#60A5FA_100%)]",
        route: "/skincare/treatment-planning",
        scanRoute: "/product-analysis",
        description: "Treatment planning",
      },
    ],
  },
  {
    title: "Makeup",
    icon: Palette,
    items: [
      {
        title: "True Tone",
        icon: Palette,
        route: "/makeup/true-tone",
        new: true,
        scanRoute: "/shade-matching",
        bg: "bg-[linear-gradient(45deg,#FBCFE8_0%,#F472B6_100%)]",
        description: "Shade matching",
      },
      {
        title: "Beauty Brief",
        icon: BookOpen,
        route: "/makeup/beauty-brief",
        scanRoute: "/none",
        bg: "bg-[linear-gradient(45deg,#E9D5FF_0%,#C084FC_100%)]",
        description: "Makeup insights",
      },
      {
        title: "Event Glam",
        icon: Star,
        route: "/makeup/event-glam",
        scanRoute: "/none",
        bg: "bg-[linear-gradient(45deg,#FECDD3_0%,#F87171_100%)]",
        description: "Occasion makeup",
      },
      {
        title: "Perfect Pair",
        icon: Brush,
        route: "/makeup/perfect-pair",
        scanRoute: "/none",
        bg: "bg-[linear-gradient(45deg,#BFDBFE_0%,#38BDF8_100%)]",
        description: "Tools guide",
      },

      {
        title: "Beauty Breakdown",
        icon: Camera,
        route: "/makeup/beauty-breakdown",
        scanRoute: "/none",
        bg: "bg-[linear-gradient(45deg,#FDE68A_0%,#FACC15_100%)]",
        description: "Product analysis",
      },
      {
        title: "Flawless Factor",
        icon: Award,
        route: "/makeup/flawless-factor",
        scanRoute: "/none",
        bg: "bg-[linear-gradient(45deg,#C7D2FE_0%,#818CF8_100%)]",
        description: "Technique refinement",
      },
    ],
  },
  {
    title: "Nutrition",
    icon: Heart,
    items: [
      {
        title: "Nutri Guide",
        icon: Salad,
        route: "/nutrition/nutri-guide",
        bg: "bg-[linear-gradient(45deg,#FBCFE8_0%,#FB7185_100%)]",
        description: "Eating guide",
      },
      {
        title: "Meal Muse",
        icon: Apple,
        route: "/nutrition/meal-muse",
        bg: "bg-[linear-gradient(45deg,#BFDBFE_0%,#60A5FA_100%)]",
        description: "Meal inspiration",
      },
      {
        title: "Supp Smart",
        icon: Pill,
        route: "/nutrition/supp-smart",
        bg: "bg-[linear-gradient(45deg,#FBCFE8_0%,#C084FC_100%)]",
        description: "Supplement guidance",
      },
    ],
  },
  {
    title: "Hair Care",
    icon: Waves,
    items: [
      {
        title: "Hair Decode",
        icon: Search,
        route: "/hair-care/hair-decode",
        bg: "bg-[linear-gradient(45deg,#BBF7D0_0%,#34D399_100%)]",
        description: "Hair analysis",
      },
      {
        title: "Formula Focus",
        icon: Beaker,
        route: "/hair-care/formula-focus",
        bg: "bg-[linear-gradient(45deg,#BFDBFE_0%,#38BDF8_100%)]",
        description: "Product formulas",
      },
      {
        title: "Tress Therapy",
        icon: Sparkles,
        route: "/hair-care/tress-therapy",
        bg: "bg-[linear-gradient(45deg,#BBF7D0_0%,#A3E635_100%)]",
        description: "Hair treatments",
      },
      {
        title: "Style Spark",
        icon: Wand2,
        route: "/hair-care/style-spark",
        bg: "bg-[linear-gradient(45deg,#FED7AA_0%,#FBBF24_100%)]",
        description: "Styling tips",
      },
    ],
  },
  {
    title: "Styling",
    icon: Shirt,
    items: [
      {
        title: "Fashion Fix",
        icon: Zap,
        route: "/styling/fashion-fix",
        bg: "bg-[linear-gradient(45deg,#FECACA_0%,#FB7185_100%)]",
        description: "Style refresh",
      },
      {
        title: "Shop Smart",
        icon: CreditCard,
        route: "/styling/shop-smart",
        bg: "bg-[linear-gradient(45deg,#FECACA_0%,#F87171_100%)]",
        description: "Shopping tips",
      },
      {
        title: "Event Edit",
        icon: Sparkles,
        route: "/styling/event-edit",
        bg: "bg-[linear-gradient(45deg,#BBF7D0_0%,#4ADE80_100%)]",
        description: "Occasion outfits",
      },
    ],
  },
  {
    title: "Wellness",
    icon: Heart,
    items: [
      {
        title: "Wellness Whisper",
        icon: Heart,
        route: "/wellness/wellness-whisper",
        bg: "bg-[linear-gradient(45deg,#C7D2FE_0%,#60A5FA_100%)]",
        description: "Lifestyle tips",
      },
      {
        title: "Fit Flow",
        icon: Dumbbell,
        route: "/wellness/fit-flow",
        bg: "bg-[linear-gradient(45deg,#FEF08A_0%,#FBBF24_100%)]",
        description: "Fitness routines",
      },
      {
        title: "Zen Zone",
        icon: Brain,
        route: "/wellness/zen-zone",
        bg: "bg-[linear-gradient(45deg,#FECDD3_0%,#FB7185_100%)]",
        description: "Mindfulness",
      },
      {
        title: "Positivity Pulse",
        icon: Sun,
        route: "/wellness/positivity-pulse",
        bg: "bg-[linear-gradient(45deg,#E9D5FF_0%,#C084FC_100%)]",
        description: "Daily positivity",
      },
      {
        title: "Stress Reset",
        icon: AlarmClock,
        route: "/wellness/stress-reset",
        bg: "bg-[linear-gradient(45deg,#FBCFE8_0%,#F472B6_100%)]",
        description: "Stress management",
      },
      {
        title: "Self Spark",
        icon: Target,
        route: "/wellness/self-spark",
        bg: "bg-[linear-gradient(45deg,#FEF08A_0%,#FBBF24_100%)]",
        description: "Personal growth",
      },
      {
        title: "Manifest Mode",
        icon: Lightbulb,
        route: "/wellness/manifest-mode",
        bg: "bg-[linear-gradient(45deg,#FDE68A_0%,#FACC15_100%)]",
        description: "Goal manifestation",
      },
    ],
  },
];

export const comingSoonItemsData = [
  // {
  //   title: "Styling",
  //   icon: Sparkles,
  //   route: "/styling",
  //   description: "Personal style recommendations and wardrobe planning",
  // },
  // {
  //   title: "Wellness",
  //   icon: Heart,
  //   route: "/wellness",
  //   description: "Holistic wellness tracking and lifestyle guidance",
  // },
  // {
  //   title: "Nutrition",
  //   icon: Utensils,
  //   route: "/nutrition",
  //   description: "Nutrition advice for healthy skin and beauty",
  // },
  // {
  //   title: "Haircare",
  //   icon: Scissors,
  //   route: "/haircare",
  //   description: "Hair analysis and personalized care routines",
  // },
];

export const resultPageData = {
  main: [
    {
      id: "chat",
      title: "Skincare",
      description: "Personalized skincare routine",
      icon: <MessageCircle />,
      route: "/chat",
      type: "skincare",
    },
  ],

  professional: [
    {
      id: "treatment-planning",
      title: "Treatment Planning",
      description: "Recommended treatments",
      icon: <Calendar />,
      route: "/treatment-planning",
      type: "treatment_planning",
    },
  ],
  insights: [
    {
      id: "trend-analysis",
      title: "Trend Analysis",
      description: "Verify trends before damaging your skin",
      icon: <TrendingUp />,
      route: "/trend-analysis",
      type: "trend_analysis",
    },
  ],
  otherCategories: [
    {
      id: "check-ingredients",
      title: "Check Ingredients",
      description: "check ingredients applying on skin",
      icon: <TriangleAlert />,
      route: "/check-ingredients",
      type: "ingredient_checker",
    },
  ],
};
