"""Add customer email and name

Revision ID: 277300ac4832
Revises: 5b922525cd8a
Create Date: 2025-08-12 12:05:24.547337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277300ac4832'
down_revision: Union[str, Sequence[str], None] = '5b922525cd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('name', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.alter_column('payments', 'stripe_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payments', 'email')
    op.drop_column('payments', 'name')
    # ### end Alembic commands ###
