"""generate different chat tables

Revision ID: 27aa65594c82
Revises: 89261187e878
Create Date: 2025-08-11 13:25:38.800186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27aa65594c82'
down_revision: Union[str, Sequence[str], None] = '89261187e878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hair_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hair_messages_user_id'), 'hair_messages', ['user_id'], unique=False)
    op.create_table('ingredient_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_messages_user_id'), 'ingredient_messages', ['user_id'], unique=False)
    op.create_table('nutrition_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_messages_user_id'), 'nutrition_messages', ['user_id'], unique=False)
    op.create_table('styling_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_styling_messages_user_id'), 'styling_messages', ['user_id'], unique=False)
    op.create_table('treatment_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_messages_user_id'), 'treatment_messages', ['user_id'], unique=False)
    op.create_table('trend_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_messages_user_id'), 'trend_messages', ['user_id'], unique=False)
    op.create_table('wellness_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_messages_user_id'), 'wellness_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wellness_messages_user_id'), table_name='wellness_messages')
    op.drop_table('wellness_messages')
    op.drop_index(op.f('ix_trend_messages_user_id'), table_name='trend_messages')
    op.drop_table('trend_messages')
    op.drop_index(op.f('ix_treatment_messages_user_id'), table_name='treatment_messages')
    op.drop_table('treatment_messages')
    op.drop_index(op.f('ix_styling_messages_user_id'), table_name='styling_messages')
    op.drop_table('styling_messages')
    op.drop_index(op.f('ix_nutrition_messages_user_id'), table_name='nutrition_messages')
    op.drop_table('nutrition_messages')
    op.drop_index(op.f('ix_ingredient_messages_user_id'), table_name='ingredient_messages')
    op.drop_table('ingredient_messages')
    op.drop_index(op.f('ix_hair_messages_user_id'), table_name='hair_messages')
    op.drop_table('hair_messages')
    # ### end Alembic commands ###
