"""Add payments + subscription fields

Revision ID: 5b922525cd8a
Revises: 8ba643ee6b39
Create Date: 2025-08-11 22:27:30.127084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b922525cd8a'
down_revision: Union[str, Sequence[str], None] = '8ba643ee6b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'payments', ['stripe_subscription_id'])
    op.add_column('user_profiles', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('subscription_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'subscription_end')
    op.drop_column('user_profiles', 'subscription_status')
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payments', 'stripe_subscription_id')
    # ### end Alembic commands ###
