"""create static table

Revision ID: 89261187e878
Revises: d891a6fae132
Create Date: 2025-08-11 00:11:48.437640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89261187e878'
down_revision: Union[str, Sequence[str], None] = 'd891a6fae132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_messages')
    # ### end Alembic commands ###
