"""add chats_table

Revision ID: 9d15502b14f8
Revises: 2e3765e712a3
Create Date: 2025-07-04 18:41:09.379335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d15502b14f8'
down_revision: Union[str, Sequence[str], None] = '2e3765e712a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('results', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_results_chat_id'), 'chat_results', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_results_user_id'), 'chat_results', ['user_id'], unique=False)
    op.drop_column('user_profiles', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_results_user_id'), table_name='chat_results')
    op.drop_index(op.f('ix_chat_results_chat_id'), table_name='chat_results')
    op.drop_table('chat_results')
    # ### end Alembic commands ###
