"""foriegn keys added

Revision ID: 9e7d7c2dabb9
Revises: 93a72870d32a
Create Date: 2025-09-30 23:46:14.147834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7d7c2dabb9'
down_revision: Union[str, Sequence[str], None] = '93a72870d32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.create_foreign_key(None, 'payments', 'user_profiles', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
