"""add email and phone to user_profiles

Revision ID: bf22aa64d75b
Revises: ab9cb57a950d
Create Date: 2025-06-28 23:07:51.860685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf22aa64d75b'
down_revision: Union[str, Sequence[str], None] = 'ab9cb57a950d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.create_unique_constraint(None, 'user_profiles', ['email'])
    op.create_unique_constraint(None, 'user_profiles', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.drop_column('user_profiles', 'phone_number')
    op.drop_column('user_profiles', 'email')
    # ### end Alembic commands ###
