"""update_b2b_tables

Revision ID: d02b71fddbfc
Revises: fe70a56d089d
Create Date: 2025-12-18 22:18:44.331657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02b71fddbfc'
down_revision: Union[str, Sequence[str], None] = 'fe70a56d089d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('b2b_face_scans', sa.Column('texture', sa.String(), nullable=True))
    op.add_column('b2b_face_scans', sa.Column('texture_confidence', sa.Float(), nullable=True))
    op.add_column('b2b_face_scans', sa.Column('under_eye', sa.Float(), nullable=True))
    op.add_column('b2b_face_scans', sa.Column('under_eye_confidence', sa.Float(), nullable=True))
    op.add_column('b2b_face_scans', sa.Column('lip_color', sa.String(), nullable=True))
    op.add_column('b2b_face_scans', sa.Column('lip_color_confidence', sa.Float(), nullable=True))
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('b2b_face_scans', 'lip_color_confidence')
    op.drop_column('b2b_face_scans', 'lip_color')
    op.drop_column('b2b_face_scans', 'under_eye_confidence')
    op.drop_column('b2b_face_scans', 'under_eye')
    op.drop_column('b2b_face_scans', 'texture_confidence')
    op.drop_column('b2b_face_scans', 'texture')
    # ### end Alembic commands ###
