"""Add profile tips

Revision ID: d8b185de62d0
Revises: 277300ac4832
Create Date: 2025-08-12 23:57:54.365872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b185de62d0'
down_revision: Union[str, Sequence[str], None] = '277300ac4832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.add_column('user_profiles', sa.Column('makeup_goal', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('nutrition_goal', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('dietary_restriction', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('wellness_focus', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('dedicate_time', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('hair_type', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('hair_concern', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('style_preference', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('styling_goal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'styling_goal')
    op.drop_column('user_profiles', 'style_preference')
    op.drop_column('user_profiles', 'hair_concern')
    op.drop_column('user_profiles', 'hair_type')
    op.drop_column('user_profiles', 'dedicate_time')
    op.drop_column('user_profiles', 'wellness_focus')
    op.drop_column('user_profiles', 'dietary_restriction')
    op.drop_column('user_profiles', 'nutrition_goal')
    op.drop_column('user_profiles', 'makeup_goal')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
