"""apply unique

Revision ID: e96fcde58f43
Revises: 05da157edf0c
Create Date: 2025-07-04 20:01:21.306606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96fcde58f43'
down_revision: Union[str, Sequence[str], None] = '05da157edf0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_chat', 'chat_results', ['user_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_chat', 'chat_results', type_='unique')
    # ### end Alembic commands ###
