"""add type name and age

Revision ID: ef5227ac97b0
Revises: 60e592354736
Create Date: 2025-06-29 15:40:24.876123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5227ac97b0'
down_revision: Union[str, Sequence[str], None] = '60e592354736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('age', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'age')
    op.drop_column('user_profiles', 'name')
    # ### end Alembic commands ###
