"""add_reviews_table

Revision ID: f9107ebc88dc
Revises: b8d4e3f1a2c6
Create Date: 2026-03-11 19:05:48.358224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9107ebc88dc'
down_revision: Union[str, Sequence[str], None] = 'b8d4e3f1a2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('brand_name', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('skin_attributes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('product_skin_benefits',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('attribute_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['skin_attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('reviewer_country', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('feature_tag', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('is_seeded', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.alter_column('b2b_clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'b2b_users', ['email'])
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'b2b_users', type_='unique')
    op.alter_column('b2b_clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('product_skin_benefits')
    op.drop_table('skin_attributes')
    op.drop_table('products')
    # ### end Alembic commands ###
