"""b2b_models

Revision ID: fe70a56d089d
Revises: 1177e7bb7e83
Create Date: 2025-12-17 19:46:15.181359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe70a56d089d'
down_revision: Union[str, Sequence[str], None] = '1177e7bb7e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b2b_api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['b2b_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_api_keys_client_id'), 'b2b_api_keys', ['client_id'], unique=False)
    op.create_table('b2b_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['b2b_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_users_client_id'), 'b2b_users', ['client_id'], unique=False)
    op.create_table('b2b_face_scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('b2b_user_id', sa.String(), nullable=False),
    sa.Column('skin_type', sa.String(), nullable=True),
    sa.Column('skin_type_confidence', sa.Float(), nullable=True),
    sa.Column('concerns', sa.JSON(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('undertone', sa.String(), nullable=True),
    sa.Column('age_range', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('lifestyle', sa.String(), nullable=True),
    sa.Column('scan_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['b2b_user_id'], ['b2b_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_b2b_face_scans_b2b_user_id'), 'b2b_face_scans', ['b2b_user_id'], unique=False)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'stripe_payment_intent_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_b2b_face_scans_b2b_user_id'), table_name='b2b_face_scans')
    op.drop_table('b2b_face_scans')
    op.drop_index(op.f('ix_b2b_users_client_id'), table_name='b2b_users')
    op.drop_table('b2b_users')
    op.drop_index(op.f('ix_b2b_api_keys_client_id'), table_name='b2b_api_keys')
    op.drop_table('b2b_api_keys')
    op.drop_table('b2b_clients')
    # ### end Alembic commands ###
